name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SCAN_MOCK: 'true'
      INBOX_DIR: "${{ runner.temp }}/inbox"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - name: Prepare inbox
        run: mkdir -p "$INBOX_DIR"
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Pack check
        run: npm run pack:check
      - name: Test
        run: npm test -- --run
