name: Release

on:
  # Publish on GitHub Release publication and on pushed version tags.
  release:
    types: [published, created]
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag/ref
        uses: actions/checkout@v4
        with:
          # Use the release tag when triggered by a release, otherwise use the pushed ref
          ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - name: Install dependencies
        run: npm ci --no-audit --no-fund
      - name: Verify build and tests
        run: |
          npm run typecheck
          npm run lint
          npm run build
          npm run pack:check
          npm test -- --run
      - name: Publish to npm (Trusted Publishing + provenance)
        env:
          # For Trusted Publishing with provenance, do NOT set NODE_AUTH_TOKEN.
          # Ensure the package is configured as a Trusted Publisher in npm for this repo.
          NPM_CONFIG_PROVENANCE: true
        run: |
          # Best practice: rebuild from source at the tagged commit; do not rely on GitHub release assets.
          npm publish --provenance --access public

      - name: Start SSH debug session on failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        timeout-minutes: 60
